project_id = "pfdeqgssdkpqexoewyyn"

[functions.send-invoice-reminder]
verify_jwt = false

[functions.send-stock-alert]
verify_jwt = false

[functions.process-scheduled-alerts]
verify_jwt = false

[functions.check-movement-changes]
verify_jwt = false

[functions.send-invitation]
verify_jwt = true
